---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy Dockerfile to host
  copy:
    src: files/Dockerfile
    dest: /tmp

- name: Copy nginx index.html to host
  template:
    src: templates/index.html.j2
    dest: /tmp/index.html

- name: Build Docker image
  command: "docker build -t {{stack_name}}-image /tmp"

- name: Run Docker container
  command: "docker run -d -p 80:80 -v /var/log/nginx:/var/log/nginx --name {{stack_name}}-container {{stack_name}}-image"
